### ISSUE TITLE
[Bug]: concurrent map write and read

### ISSUE THREAD

**Issue by Rui-i** [panjf2000/gnet#632] opened 2024-08-08 06:25 UTC
### Actions I've taken before I'm here

- [X] I've thoroughly read the documentations on this issue but still have no clue.
- [X] I've searched the Github Issues but didn't find any duplicate issues that have been resolved.
- [X] I've searched the internet for this issue but didn't find anything helpful.

### What happened?

![img_v3_02di_bffb712b-b36b-4fa6-bc38-425920f0fcch](https://github.com/user-attachments/assets/036be0cb-291b-4709-b8be-e5b8ab0c5233)
I have encounter panic `fatal error: concurrent map read and map write` when using this. 

### Major version of gnet

v2

### Specific version of gnet

v2.5.7

### Operating system

Linux

### OS version

Ubuntu 20.04

### Go version

go1.21

### Relevant log output

```shell
fatal error: concurrent map read and map write

goroutine 77 [running, locked to thread]:
github.com/panjf2000/gnet/v2.(*connMatrix).getConn(...)
        /github.com/panjf2000/gnet/v2@v2.5.7/conn_map.go:66
github.com/panjf2000/gnet/v2.(*eventloop).close(0xc00080ab00, 0xc009306d20, {0x23ffc80, 0xc00b44c440})
        /github.com/panjf2000/gnet/v2@v2.5.7/eventloop_unix.go:230 +0x70
github.com/panjf2000/gnet/v2.(*eventloop).read(0xc00080ab00, 0xc009306d20)
        /github.com/panjf2000/gnet/v2@v2.5.7/eventloop_unix.go:139 +0x310
github.com/panjf2000/gnet/v2.(*conn).processIO(0xc009306d20, 0xc00087d650?, 0x19, 0x0?)
        /github.com/panjf2000/gnet/v2@v2.5.7/connection_linux.go:54 +0xa5
github.com/panjf2000/gnet/v2.(*eventloop).orbit.func1(0x1af, 0x19, 0x0)
        /github.com/panjf2000/gnet/v2@v2.5.7/reactor_default.go:66 +0x1b6
github.com/panjf2000/gnet/v2/internal/netpoll.(*Poller).Polling(0xc000c837a0, 0xc00177df28)
        /github.com/panjf2000/gnet/v2@v2.5.7/internal/netpoll/poller_epoll_default.go:136 +0x26c
github.com/panjf2000/gnet/v2.(*eventloop).orbit(0xc00080ab00)
        /github.com/panjf2000/gnet/v2@v2.5.7/reactor_default.go:54 +0x97
```

### How to Reproduce

This behavior only occur by chance, there is no reproduce steps.
As long as its is running with multi thread there will be chance for this panic to occur. 

### Does this issue reproduce with the latest release?

It can reproduce with the latest release

**Comment by panjf2000** [comment] 2024-08-08 08:48
Is that all the fatal log? It contains within it all the goroutines accessing the map.

Also, could you provide a example showing how you configure and use `gnet`?

**Comment by panjf2000** [comment] 2024-08-08 12:12
Thanks for the new details. But, I have no clue about this at the moment. We may need more debugging. Could you try to use [`WithReusePort`](https://pkg.go.dev/github.com/panjf2000/gnet/v2#WithReusePort) or downgrade to v2.4.2 and see if this issue still exists?

**Comment by panjf2000** [comment] 2024-09-09 03:46
Duplicate of #463 #479 #525 #577

**Closed by panjf2000** 2024-09-09 03:46 UTC
Labels: bug, waiting for response, needs investigation, needs more info
